export const SET_CART = 'SET_CART';
export const ADD_CART = 'ADD_CART';
export const INSCREASE_CART = 'INSCREASE_CART';
export const DESCREASE_CART = 'DESCREASE_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';
